### ISSUE TITLE
Combo of attributes "hidden" and "defined by system": CLI won't compile

### ISSUE THREAD

**Issue by WheelyWonka** [Tractr/boilerplate-ngx-components#1]
**Describe the bug**
The Angular CLI won't compile the app in dev mode (`npm start`) caused by a combo of attributes "hidden" and "defined by system" in a field.

**To Reproduce**
1. Create a new model
2. Add a field, any name, any type
3. Add attributes "Hidden" + "Defined by system" to this field
4. Generate Ngx-components code: `hpf generate`
5. In Ngx-component folder: `npm i && npm start`
6. The CLI won't compile.

**Expected behavior**
The CLI compiles correctly.

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser: Chrome

**Comment by EdouardDem** [comment]
This issue has been resolved when migrating the boilerplate to Ant Design
